### ISSUE TITLE
Twitch App opens but stays minimized/in tray.

### ISSUE THREAD

**Issue by 0x526f6d656f** [portapps/twitch-portable#1]
The twitch app basically "opens" without an error, but it only has a tray icon. There is no GUI popping up when right-clicking the icon and pressing "Open Twitch".

**Comment by crazy-max** [comment]
Please read and apply the [SUPPORT page](https://github.com/portapps/twitch-portable/blob/master/.github/SUPPORT.md). Thanks.

**Comment by 0x526f6d656f** [comment]
### Behaviour

#### Steps to reproduce this issue

1. Starting twitch-portable.exe

#### Expected behaviour

> The twitch app/gui should open

#### Actual behaviour

> Only the app icon shows up in the system tray, opening it from there doesn't do anything.

Eventlog says ..\Twitch\Bin\Electron\TwitchUI.exe is restricted behind a software policy.

### Configuration

**App release / arch (ex. 0.0.298-14 x64)** : 7.5.6591.2326 x64

**Operating system (ex. Windows 10 Pro 64 bits)** : Win 10 Pro 64bit

**Winver screenshot** : https://i.imgur.com/ut102un.png

### Logs

INFO : 2018/02/05 08:31:37.550541 main.go:78: --------
INFO : 2018/02/05 08:31:37.708957 main.go:79: Starting Twitch...
INFO : 2018/02/05 08:31:37.708957 main.go:80: Current path: C:\Users\maierrom\Nextcloud\Portable Apps\Twitch
INFO : 2018/02/05 08:31:37.708957 main.go:156: Process: C:\Users\maierrom\Nextcloud\Portable Apps\Twitch\Bin\Twitch.exe
INFO : 2018/02/05 08:31:37.708957 main.go:157: Args: 
INFO : 2018/02/05 08:31:37.708957 main.go:158: Working dir: C:\Users\maierrom\Nextcloud\Portable Apps\Twitch\Bin
INFO : 2018/02/05 08:31:37.708957 main.go:159: Data path: 
INFO : 2018/02/05 08:31:37.708957 main.go:161: Launch Twitch...
INFO : 2018/02/05 08:31:37.708957 main.go:168: Exec C:\Users\maierrom\Nextcloud\Portable Apps\Twitch\Bin\Twitch.exe 
05.02.2018 08:31:39|Warn |Logger.set_Level|The current logging level has been changed to Trace.

**Comment by crazy-max** [comment]
Hi @atemerino, i will take a look on your issue asap.
Btw, is the regular app working on your computer : http://app.twitch.tv/ ?

Thanks
